[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gitco"
dynamic = ["version"]
description = "A simple CLI tool for intelligent OSS fork management and contribution discovery"
readme = {file = "README.md", content-type = "text/markdown"}
license = {text = "MIT"}
authors = [
    {name = "FortyOne Technologies Inc.", email = "fortyone.technologies@gmail.com"}
]
maintainers = [
    {name = "FortyOne Technologies Inc.", email = "fortyone.technologies@gmail.com"}
]
keywords = [
    "git", "cli", "oss", "fork-management", "contributions",
    "ai", "llm", "automation", "github", "sync", "analysis",
    "repository-management", "open-source", "developer-tools"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Version Control :: Git",
    "Topic :: Software Development :: Version Control",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities",
    "Typing :: Typed",
]
requires-python = ">=3.9"
dependencies = [
    "click>=8.0.0",
    "pyyaml>=6.0",
    "gitpython>=3.1.0",
    "requests>=2.28.0",
    "rich>=13.0.0",
    "openai>=1.0.0",
    "tiktoken>=0.5.0",
    "pygithub>=1.59.0",
    "psutil>=5.9.0",
    "jinja2>=3.0.0",
    "urllib3>=1.26.0",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.1.0",
    "black>=23.0.0",
    "pre-commit>=3.0.0",
    "yamllint>=1.35.0",
    "build>=1.0.0",
    "twine>=4.0.0",
    "check-manifest>=0.49",
    "pip-audit>=2.6.0",
    "bandit>=1.7.0",
    "detect-secrets>=1.5.0",
]

docs = [
    "sphinx>=6.0.0",
    "sphinx-rtd-theme>=1.2.0",
    "myst-parser>=1.0.0",
]

[project.urls]
Homepage = "https://github.com/41technologies/gitco"
Documentation = "https://github.com/41technologies/gitco#readme"
Repository = "https://github.com/41technologies/gitco.git"
"Source Code" = "https://github.com/41technologies/gitco"
"Bug Tracker" = "https://github.com/41technologies/gitco/issues"
"Feature Requests" = "https://github.com/41technologies/gitco/issues/new?template=feature_request.md"
"Security" = "https://github.com/41technologies/gitco/security/policy"
"Changelog" = "https://github.com/41technologies/gitco/blob/main/CHANGELOG.md"
"Releases" = "https://github.com/41technologies/gitco/releases"
"CI/CD" = "https://github.com/41technologies/gitco/actions"


[project.scripts]
gitco = "gitco.cli:main"

[project.entry-points."console_scripts"]
gitco = "gitco.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.package-data]
gitco = []

[tool.setuptools.exclude-package-data]
"*" = ["*.pyc", "*.pyo", "*.pyd", "__pycache__", "*.so", "*.c"]

[tool.setuptools.dynamic]
version = {attr = "gitco.__version__"}

[tool.ruff]
target-version = "py39"
line-length = 88

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings (includes W292 - missing newline at end of file)
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg

  | \.tox
  | \.venv
  | build
  | dist
)/
'''
