"""Regex patterns for GitCo detection."""

from .constants import (
    BREAKING_CHANGE_PATTERNS,
    CRITICAL_SECURITY_PATTERNS,
    DEPRECATION_PATTERNS,
    HIGH_DEPRECATION_PATTERNS,
    HIGH_SECURITY_PATTERNS,
    HIGH_SEVERITY_PATTERNS,
    MEDIUM_DEPRECATION_PATTERNS,
    MEDIUM_SECURITY_PATTERNS,
    MEDIUM_SEVERITY_PATTERNS,
    SECURITY_PATTERNS,
)

__all__ = [
    "SECURITY_PATTERNS",
    "DEPRECATION_PATTERNS",
    "BREAKING_CHANGE_PATTERNS",
    "HIGH_SEVERITY_PATTERNS",
    "MEDIUM_SEVERITY_PATTERNS",
    "CRITICAL_SECURITY_PATTERNS",
    "HIGH_SECURITY_PATTERNS",
    "MEDIUM_SECURITY_PATTERNS",
    "HIGH_DEPRECATION_PATTERNS",
    "MEDIUM_DEPRECATION_PATTERNS",
]
