name: PyPI Package Publishing

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g., 1.0.0)"
        required: true
        type: string
      publish_to_pypi:
        description: "Publish to PyPI"
        required: false
        default: true
        type: boolean

      dry_run:
        description: "Dry run (build only, no publish)"
        required: false
        default: false
        type: boolean
  push:
    tags:
      - "v*"

env:
  PYTHON_VERSION: "3.12"

# Security: Define permissions for the workflow
permissions:
  contents: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit detect-secrets pip-audit safety

      - name: Run comprehensive security scan
        run: |
          echo "🔒 Running comprehensive security scan..."

          # Scan for secrets in code
          echo "🔍 Scanning for secrets..."
          detect-secrets scan --baseline .secrets.baseline . > detect-secrets-report.json || true

          # Run bandit security analysis
          echo "🔍 Running bandit security analysis..."
          bandit -r src/ -f json -o bandit-report.json || true

          # Check for dependency vulnerabilities
          echo "🔍 Checking dependency vulnerabilities..."
          pip-audit --format json --output pip-audit-report.json || true

          # Additional safety checks
          echo "🔍 Running safety checks..."
          safety check --json --output safety-report.json || true

          # Check for hardcoded secrets in configuration
          echo "🔍 Checking for hardcoded secrets..."
          if grep -r "sk-|pk_|ghp_|gho_|ghu_|ghs_|ghr_" src/; then
            echo "❌ Potential secrets found in code"
            exit 1
          fi

          echo "✅ Security scan completed"

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            detect-secrets-report.json
            bandit-report.json
            pip-audit-report.json
            safety-report.json

  validate:
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run pre-upload validation
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

        run: |
          echo "🔍 Running comprehensive pre-upload validation..."

          # Make script executable
          chmod +x scripts/pre-upload-validation.sh

          # Run pre-upload validation
          ./scripts/pre-upload-validation.sh --all

          echo "✅ Pre-upload validation completed successfully"

      - name: Validate PyPI authentication
        run: |
          # Check if PyPI tokens are properly configured
          if [ "${{ github.event.inputs.publish_to_pypi }}" == "true" ] || \
             [ "${{ github.event_name }}" == "push" ]; then
            if [ -z "${{ secrets.PYPI_API_TOKEN }}" ]; then
              echo "⚠️  PyPI authentication not configured"
              echo "Configure PYPI_API_TOKEN secret for PyPI publishing"
              echo "Get your token from: https://pypi.org/manage/account/token/"
              exit 1
            fi
          fi

          echo "✅ PyPI authentication validation passed"

      - name: Check for version conflicts
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            # Extract version from tag (remove 'v' prefix)
            VERSION=${GITHUB_REF#refs/tags/v}
          fi

          echo "📦 Building version: $VERSION"

          # Validate version format
          if ! echo "$VERSION" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?(\+[a-zA-Z0-9.-]+)?$'; then
            echo "❌ Invalid version format: $VERSION"
            echo "Version must follow semantic versioning (e.g., 1.0.0, 1.0.0-alpha.1)"
            exit 1
          fi

          # Check if version already exists on PyPI
          if pip index versions gitco | grep -q "$VERSION"; then
            echo "⚠️  Version $VERSION already exists on PyPI"
            if [ "${{ github.event.inputs.dry_run }}" != "true" ] && [ "${{ github.event_name }}" == "push" ]; then
              echo "❌ Cannot publish duplicate version"
              exit 1
            fi
          else
            echo "✅ Version $VERSION is available for publishing"
          fi

  build:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine check-manifest pip-audit

      - name: Clean build environment
        run: |
          # Clean any existing builds
          rm -rf dist/ build/ *.egg-info/
          echo "🧹 Build environment cleaned"

      - name: Build package
        run: |
          # Build both wheel and source distribution
          python -m build --wheel --sdist

          # List build artifacts
          echo "📦 Build artifacts:"
          ls -la dist/

          # Show package contents
          for file in dist/*; do
            echo "📋 Contents of $file:"
            if [[ $file == *.whl ]]; then
              unzip -l "$file" | head -10
            elif [[ $file == *.tar.gz ]]; then
              tar -tzf "$file" | head -10
            fi
            echo ""
          done

      - name: Validate package security
        run: |
          # Check for security issues
          pip-audit --format json --output pip-audit.json || true

          # Validate package with twine
          twine check dist/*

          # Check package size and contents
          for file in dist/*; do
            size=$(du -h "$file" | cut -f1)
            echo "📦 $file: $size"

            # Check for suspicious files in package
            if [[ $file == *.whl ]]; then
              if unzip -l "$file" | grep -E "\.(key|pem|crt|p12|pfx|pwd|pass|secret|token)"; then
                echo "⚠️  Warning: Potential secrets found in package"
              fi
            fi
          done

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run != 'true') ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to_pypi == 'true') ||
          (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
        run: |
          if [ -z "$TWINE_PASSWORD" ]; then
            echo "⚠️  Skipping PyPI publishing - PYPI_API_TOKEN not configured"
            echo "To enable PyPI publishing, add PYPI_API_TOKEN secret"
            echo "Get your token from: https://pypi.org/manage/account/token/"
            exit 0
          fi

          echo "🚀 Publishing to PyPI..."

          # Validate token format (PyPI tokens start with pypi-)
          if [[ ! "$TWINE_PASSWORD" =~ ^pypi- ]]; then
            echo "❌ Invalid PyPI token format"
            echo "PyPI tokens should start with 'pypi-'"
            exit 1
          fi

          # Upload with retry mechanism
          for attempt in {1..3}; do
            echo "📤 Upload attempt $attempt/3"

            if twine upload --verbose dist/*; then
              echo "✅ Successfully published to PyPI"
              echo "📦 Package URL: https://pypi.org/project/gitco/"
              break
            else
              echo "⚠️  Upload attempt $attempt failed"
              if [ $attempt -lt 3 ]; then
                echo "⏳ Waiting 30 seconds before retry..."
                sleep 30
              else
                echo "❌ All upload attempts failed"
                exit 1
              fi
            fi
          done

      - name: Verify PyPI availability
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to_pypi == 'true') ||
          (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/v}
          fi

          echo "⏳ Waiting for PyPI to process upload..."
          sleep 60

          echo "🔍 Verifying package availability on PyPI..."

          # Test package installation from PyPI
          python -m venv verify-env
          source verify-env/bin/activate

          if pip install gitco==$VERSION; then
            echo "✅ Package successfully installed from PyPI"
            python -c "import gitco; print(f'✅ Package version {gitco.__version__} imported successfully')"
            gitco --help
          else
            echo "❌ Failed to install package from PyPI"
            exit 1
          fi

          deactivate
          rm -rf verify-env

  notify:
    runs-on: ubuntu-latest
    needs: [build, publish]
    if: always()
    steps:
      - name: Handle success
        if: needs.publish.result == 'success' || (needs.publish.result == 'skipped' && needs.build.result == 'success')
        run: |
          echo "✅ Package build and publish completed successfully"
          echo "📦 PyPI: https://pypi.org/project/gitco/"

          echo "📖 Documentation: https://github.com/41technologies/gitco#readme"
          echo "🔒 Security: All security checks passed"

      - name: Handle failure
        if: needs.publish.result == 'failure' || needs.build.result == 'failure'
        run: |
          echo "❌ Package build or publish failed"
          echo "🔍 Check the workflow logs for details"
          echo "📧 Notify maintainers of the failure"
          echo "🔒 Review security scan reports if available"

      - name: Handle dry run
        if: github.event.inputs.dry_run == 'true'
        run: |
          echo "🧪 Dry run completed - package built but not published"
          echo "📦 Build artifacts are available for download"
          echo "🔒 Security scan completed successfully"
